coverage:
  status:
    project:
      default:
        # Flip `target` to 100% once coverage reaches it.
        target: auto
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

comment:
  layout: "condensed_header, diff, flags, files"
  behavior: default
  require_changes: false
