/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 13
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 26
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_inline_handler_content = 2,
  sym_newline = 3,
  sym__indent = 4,
  sym_handler_content = 5,
  sym_comment = 6,
  anon_sym_BQUOTE_BQUOTE_BQUOTE = 7,
  sym_code_body = 8,
  sym_string = 9,
  sym_regex = 10,
  sym_character_class = 11,
  sym_type_marker = 12,
  sym_arrow = 13,
  sym_operator = 14,
  sym_number = 15,
  sym_punctuation = 16,
  sym_program = 17,
  sym__line = 18,
  sym__hera_items = 19,
  sym__item = 20,
  sym_inline_handler = 21,
  sym_handler_line = 22,
  sym_code_block = 23,
  aux_sym_program_repeat1 = 24,
  aux_sym__hera_items_repeat1 = 25,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_inline_handler_content] = "inline_handler_content",
  [sym_newline] = "newline",
  [sym__indent] = "_indent",
  [sym_handler_content] = "handler_content",
  [sym_comment] = "comment",
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = "```",
  [sym_code_body] = "code_body",
  [sym_string] = "string",
  [sym_regex] = "regex",
  [sym_character_class] = "character_class",
  [sym_type_marker] = "type_marker",
  [sym_arrow] = "arrow",
  [sym_operator] = "operator",
  [sym_number] = "number",
  [sym_punctuation] = "punctuation",
  [sym_program] = "program",
  [sym__line] = "_line",
  [sym__hera_items] = "_hera_items",
  [sym__item] = "_item",
  [sym_inline_handler] = "inline_handler",
  [sym_handler_line] = "handler_line",
  [sym_code_block] = "code_block",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym__hera_items_repeat1] = "_hera_items_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_inline_handler_content] = sym_inline_handler_content,
  [sym_newline] = sym_newline,
  [sym__indent] = sym__indent,
  [sym_handler_content] = sym_handler_content,
  [sym_comment] = sym_comment,
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = anon_sym_BQUOTE_BQUOTE_BQUOTE,
  [sym_code_body] = sym_code_body,
  [sym_string] = sym_string,
  [sym_regex] = sym_regex,
  [sym_character_class] = sym_character_class,
  [sym_type_marker] = sym_type_marker,
  [sym_arrow] = sym_arrow,
  [sym_operator] = sym_operator,
  [sym_number] = sym_number,
  [sym_punctuation] = sym_punctuation,
  [sym_program] = sym_program,
  [sym__line] = sym__line,
  [sym__hera_items] = sym__hera_items,
  [sym__item] = sym__item,
  [sym_inline_handler] = sym_inline_handler,
  [sym_handler_line] = sym_handler_line,
  [sym_code_block] = sym_code_block,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym__hera_items_repeat1] = aux_sym__hera_items_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_handler_content] = {
    .visible = true,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym_handler_content] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BQUOTE_BQUOTE_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_code_body] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_regex] = {
    .visible = true,
    .named = true,
  },
  [sym_character_class] = {
    .visible = true,
    .named = true,
  },
  [sym_type_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__hera_items] = {
    .visible = false,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_inline_handler] = {
    .visible = true,
    .named = true,
  },
  [sym_handler_line] = {
    .visible = true,
    .named = true,
  },
  [sym_code_block] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__hera_items_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_content, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\n', 36,
        '"', 20,
        '#', 18,
        '-', 24,
        '/', 25,
        ':', 23,
        '[', 26,
        '`', 28,
        '\t', 19,
        ' ', 19,
        '!', 34,
        '$', 34,
        '&', 34,
        '*', 34,
        '+', 34,
        '?', 34,
        '|', 34,
        '(', 34,
        ')', 34,
        ',', 34,
        '.', 34,
        ';', 34,
        ']', 34,
        '{', 34,
        '}', 34,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (lookahead != 0) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(50);
      END_STATE();
    case 4:
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '`') ADVANCE(41);
      END_STATE();
    case 6:
      if (lookahead == '`') ADVANCE(15);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 7:
      if (lookahead == '`') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      END_STATE();
    case 10:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 12:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 13:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 14:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '`') ADVANCE(43);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\n', 36,
        '"', 1,
        '#', 40,
        '-', 3,
        '/', 54,
        ':', 53,
        '[', 59,
        '`', 7,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(16);
      if (('!' <= lookahead && lookahead <= '$') ||
          lookahead == '&' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '?' ||
          lookahead == '|') ADVANCE(52);
      if (('(' <= lookahead && lookahead <= '.') ||
          lookahead == ';' ||
          lookahead == ']' ||
          ('{' <= lookahead && lookahead <= '}')) ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '\r') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_inline_handler_content);
      ADVANCE_MAP(
        '"', 20,
        '#', 18,
        '-', 24,
        '/', 25,
        ':', 23,
        '[', 26,
        '`', 28,
        '\t', 19,
        ' ', 19,
        '!', 34,
        '$', 34,
        '&', 34,
        '*', 34,
        '+', 34,
        '?', 34,
        '|', 34,
        '(', 34,
        ')', 34,
        ',', 34,
        '.', 34,
        ';', 34,
        ']', 34,
        '{', 34,
        '}', 34,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '"') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '.') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '/') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '>') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '\\') ADVANCE(35);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '/') ADVANCE(34);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(22);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '\\') ADVANCE(33);
      if (lookahead == ']') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '`') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '`') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '?') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_inline_handler_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(22);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_newline);
      if (lookahead == '\n') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__indent);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_handler_content);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_handler_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BQUOTE_BQUOTE_BQUOTE);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_code_body);
      if (lookahead == '`') ADVANCE(6);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_regex);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_character_class);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_character_class);
      if (lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '?') ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_type_marker);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_type_marker);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_arrow);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_arrow);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_operator);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == ':') ADVANCE(48);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '/') ADVANCE(2);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_punctuation);
      if (lookahead == '\\') ADVANCE(14);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 16},
  [2] = {.lex_state = 16},
  [3] = {.lex_state = 16},
  [4] = {.lex_state = 16},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 16},
  [7] = {.lex_state = 16},
  [8] = {.lex_state = 16},
  [9] = {.lex_state = 38},
  [10] = {.lex_state = 43},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 16},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_inline_handler_content] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_regex] = ACTIONS(1),
    [sym_character_class] = ACTIONS(1),
    [sym_type_marker] = ACTIONS(1),
    [sym_arrow] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_program] = STATE(11),
    [sym__line] = STATE(2),
    [sym__hera_items] = STATE(2),
    [sym__item] = STATE(2),
    [sym_inline_handler] = STATE(2),
    [sym_handler_line] = STATE(2),
    [sym_code_block] = STATE(2),
    [aux_sym_program_repeat1] = STATE(2),
    [aux_sym__hera_items_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_newline] = ACTIONS(7),
    [sym__indent] = ACTIONS(9),
    [sym_comment] = ACTIONS(5),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(11),
    [sym_string] = ACTIONS(5),
    [sym_regex] = ACTIONS(5),
    [sym_character_class] = ACTIONS(5),
    [sym_type_marker] = ACTIONS(5),
    [sym_arrow] = ACTIONS(13),
    [sym_operator] = ACTIONS(7),
    [sym_number] = ACTIONS(5),
    [sym_punctuation] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__line] = STATE(3),
    [sym__hera_items] = STATE(3),
    [sym__item] = STATE(3),
    [sym_inline_handler] = STATE(3),
    [sym_handler_line] = STATE(3),
    [sym_code_block] = STATE(3),
    [aux_sym_program_repeat1] = STATE(3),
    [aux_sym__hera_items_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_newline] = ACTIONS(19),
    [sym__indent] = ACTIONS(9),
    [sym_comment] = ACTIONS(17),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(11),
    [sym_string] = ACTIONS(17),
    [sym_regex] = ACTIONS(17),
    [sym_character_class] = ACTIONS(17),
    [sym_type_marker] = ACTIONS(17),
    [sym_arrow] = ACTIONS(13),
    [sym_operator] = ACTIONS(19),
    [sym_number] = ACTIONS(17),
    [sym_punctuation] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym__line] = STATE(3),
    [sym__hera_items] = STATE(3),
    [sym__item] = STATE(3),
    [sym_inline_handler] = STATE(3),
    [sym_handler_line] = STATE(3),
    [sym_code_block] = STATE(3),
    [aux_sym_program_repeat1] = STATE(3),
    [aux_sym__hera_items_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
    [sym_newline] = ACTIONS(26),
    [sym__indent] = ACTIONS(29),
    [sym_comment] = ACTIONS(23),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(32),
    [sym_string] = ACTIONS(23),
    [sym_regex] = ACTIONS(23),
    [sym_character_class] = ACTIONS(23),
    [sym_type_marker] = ACTIONS(23),
    [sym_arrow] = ACTIONS(35),
    [sym_operator] = ACTIONS(26),
    [sym_number] = ACTIONS(23),
    [sym_punctuation] = ACTIONS(26),
  },
  [STATE(4)] = {
    [sym__item] = STATE(4),
    [sym_inline_handler] = STATE(4),
    [sym_code_block] = STATE(4),
    [aux_sym__hera_items_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(38),
    [sym_identifier] = ACTIONS(40),
    [sym_newline] = ACTIONS(43),
    [sym__indent] = ACTIONS(38),
    [sym_comment] = ACTIONS(40),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(45),
    [sym_string] = ACTIONS(40),
    [sym_regex] = ACTIONS(40),
    [sym_character_class] = ACTIONS(40),
    [sym_type_marker] = ACTIONS(40),
    [sym_arrow] = ACTIONS(48),
    [sym_operator] = ACTIONS(51),
    [sym_number] = ACTIONS(40),
    [sym_punctuation] = ACTIONS(51),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(54),
    [sym_identifier] = ACTIONS(56),
    [sym_inline_handler_content] = ACTIONS(58),
    [sym_newline] = ACTIONS(56),
    [sym__indent] = ACTIONS(56),
    [sym_comment] = ACTIONS(56),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(56),
    [sym_string] = ACTIONS(56),
    [sym_regex] = ACTIONS(56),
    [sym_character_class] = ACTIONS(56),
    [sym_type_marker] = ACTIONS(56),
    [sym_arrow] = ACTIONS(56),
    [sym_operator] = ACTIONS(56),
    [sym_number] = ACTIONS(56),
    [sym_punctuation] = ACTIONS(56),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(60),
    [sym_identifier] = ACTIONS(60),
    [sym_newline] = ACTIONS(62),
    [sym__indent] = ACTIONS(60),
    [sym_comment] = ACTIONS(60),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(60),
    [sym_string] = ACTIONS(60),
    [sym_regex] = ACTIONS(60),
    [sym_character_class] = ACTIONS(60),
    [sym_type_marker] = ACTIONS(60),
    [sym_arrow] = ACTIONS(60),
    [sym_operator] = ACTIONS(62),
    [sym_number] = ACTIONS(60),
    [sym_punctuation] = ACTIONS(62),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_identifier] = ACTIONS(64),
    [sym_newline] = ACTIONS(66),
    [sym__indent] = ACTIONS(64),
    [sym_comment] = ACTIONS(64),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(64),
    [sym_string] = ACTIONS(64),
    [sym_regex] = ACTIONS(64),
    [sym_character_class] = ACTIONS(64),
    [sym_type_marker] = ACTIONS(64),
    [sym_arrow] = ACTIONS(64),
    [sym_operator] = ACTIONS(66),
    [sym_number] = ACTIONS(64),
    [sym_punctuation] = ACTIONS(66),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(68),
    [sym_identifier] = ACTIONS(68),
    [sym_newline] = ACTIONS(70),
    [sym__indent] = ACTIONS(68),
    [sym_comment] = ACTIONS(68),
    [anon_sym_BQUOTE_BQUOTE_BQUOTE] = ACTIONS(68),
    [sym_string] = ACTIONS(68),
    [sym_regex] = ACTIONS(68),
    [sym_character_class] = ACTIONS(68),
    [sym_type_marker] = ACTIONS(68),
    [sym_arrow] = ACTIONS(68),
    [sym_operator] = ACTIONS(70),
    [sym_number] = ACTIONS(68),
    [sym_punctuation] = ACTIONS(70),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(72), 1,
      sym_handler_content,
  [4] = 1,
    ACTIONS(74), 1,
      sym_code_body,
  [8] = 1,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
  [12] = 1,
    ACTIONS(78), 1,
      anon_sym_BQUOTE_BQUOTE_BQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 4,
  [SMALL_STATE(11)] = 8,
  [SMALL_STATE(12)] = 12,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__hera_items_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hera_items_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__hera_items_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hera_items_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__hera_items_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__hera_items_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__item, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_handler_line, 2, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_handler_line, 2, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_handler, 2, 0, 1),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_handler, 2, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code_block, 3, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code_block, 3, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [76] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hera(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hera",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
