id = "civet"
name = "Civet"
description = "Civet language support for Zed"
version = "0.0.1"
schema_version = 1
authors = ["Daniel X Moore"]
repository = "https://github.com/DanielXMoore/Civet"

[grammars.civet]
repository = "file:///home/daniel/apps/Civet"
rev = "d52503d1bf2a4e4328a5de018090c81a5abf1029"
path = "lsp/tree-sitter"

[language_servers.civet-lsp]
name = "Civet LSP"
languages = ["Civet"]
