id = "civet"
name = "Civet"
description = "Civet language support for Zed"
version = "0.0.1"
schema_version = 1
authors = ["Daniel X Moore"]
repository = "https://github.com/DanielXMoore/Civet"

[grammars.civet]
repository = "file:///home/daniel/apps/Civet"
rev = "5ae580bdbcaa984ec14297d21b8c03027f45b9a9"
path = "lsp/tree-sitter"

[language_servers.civet-lsp]
name = "Civet LSP"
languages = ["Civet"]
