id = "civet"
name = "Civet"
description = "Civet language support for Zed"
version = "0.0.1"
schema_version = 1
authors = ["Daniel X Moore"]
repository = "https://github.com/DanielXMoore/Civet"

[grammars.civet]
repository = "file:///home/daniel/apps/Civet"
rev = "7d8b760a12fb90be1785c9278ba98a98c910d2c9"
path = "lsp/tree-sitter"

[language_servers.civet-lsp]
name = "Civet LSP"
languages = ["Civet"]
