on:
  push:
    branches:
      - main
    paths:
      - 'lsp/**'
  pull_request:
    paths:
      - 'lsp/**'

name: LSP

jobs:
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0
          run_install: false

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and test
        run: pnpm build && pnpm test && pnpm e2e
        working-directory: lsp
